export const CHECKLIST_REVIEWS_FETCHING_START = 'checklist_reviews_fetching_start';
export const CHECKLIST_REVIEWS_FETCHING_SUCCESS = 'checklist_reviews_fetching_success';
export const CHECKLIST_REVIEWS_FETCHING_FAILURE = 'checklist_reviews_fetching_failure';